server:
  port: 3535
spring:
  datasource:
    url: jdbc:mysql://localhost:8989/DB?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  security:
    user:
      name: bayram
      password: bayram123